import Head from 'next/head'
import Payment from '../components/Payment'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Bitnovo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/Vgqm5nj/channels4-profile.jpg" />
      </Head>

      <main>
        <Payment/>
      </main>
        
    </div>
  )
}
